UniPsg.Web.UI.PAS/Controllers/FlowLogController.cs
using System.Web.Mvc;
using UniPsg.Model.PAS.ViewModels;
using UniPsg.Web.UI.PAS.Models;

namespace UniPsg.Web.UI.PAS.Controllers
{
    public class FlowLogController : Controller
    {
        private FlowLogClient client = new FlowLogClient();
       
        // GET: FlowLog
        public ActionResult Index()
        {

            ViewBag.ListClients = client.FindAll();
            return View();
        }
        // GET: FlowLog/Create
        [HttpGet]
        public ActionResult Create()
        {            
            return View("Create");
        }

        // POST: FlowLog/Create    
        [HttpPost]
        public ActionResult Create(FlowLogViewModel models)
        {

            client.Create(models);
            return RedirectToAction("Index");
        }


        // GET: FlowLog/Edit/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Edit(int id)
        {
            FlowLogViewModel models = new FlowLogViewModel();
            models = client.Find(id);
            return View("Edit", models);
        }

        // GET: FlowLog/Edit/5    
        [HttpPost]
        public ActionResult Edit(FlowLogViewModel models)
        {
            client.Edit(models);
            return RedirectToAction("Index");
        }

        // GET: FlowLog/Delete/5    
        public ActionResult Delete(int id)
        {

            client.Delete(id);
            return RedirectToAction("Index");
        }

        // GET: FlowLog/Detail/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Detail(int id)
        {
            FlowLogViewModel models = new FlowLogViewModel();
            models = client.Find(id);
            return View("Detail", models);
        }

    }
}

UniPsg.Web.UI.PAS/Views/FlowLog/Create.cshtml
@model UniPsg.Model.PAS.ViewModels.FlowLogViewModel
@{
    ViewBag.Title = "流程修改記錄新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5><i class="fa fa-key" aria-hidden="true"> &nbsp;管理設定</i>  &nbsp;&gt;&nbsp; <a href="@Url.Action("Index","FlowLog")">流程修改記錄</a>  &nbsp;&gt;&nbsp; 流程修改記錄新增 </h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <hr />
    @using (Html.BeginForm("Create", "Role", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.BeforContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.BeforContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.BeforContent, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.AfterContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.AfterContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.AfterContent, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="~/FlowLog" class="btn btn-warning">不儲存退出</a>
                <input type="submit" value="儲存" class="btn btn-success" />               
                @Html.HiddenFor(m => m.Creator, new { @Value = @User.Identity.Name })               
            </div>
        </div>
    }
</div>

UniPsg.Web.UI.PAS/Views/FlowLog/Detail.cshtml
@model UniPsg.Model.PAS.ViewModels.FlowLogViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detail</title>
</head>
<body>
    <div>
        <h4>FlowLogViewModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.BeforContent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.BeforContent)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AfterContent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AfterContent)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Creator)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Creator)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

UniPsg.Web.UI.PAS/Views/FlowLog/Edit.cshtml
@model UniPsg.Model.PAS.ViewModels.FlowLogViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>FlowLogViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.BeforContent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BeforContent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BeforContent, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AfterContent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AfterContent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AfterContent, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

UniPsg.Web.UI.PAS/Views/FlowLog/Index.cshtml
@model IEnumerable<UniPsg.Model.PAS.ViewModels.FlowLogViewModel>


@{
    ViewBag.Title = "流程修改記錄清單";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5><i class="fa fa-key" aria-hidden="true"> &nbsp;管理設定</i>  &nbsp;&gt;&nbsp; <a href="@Url.Action("Index","FlowLog")">流程修改記錄</a></h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <div align="left"><i class="fa fa-plus" aria-hidden="true"><a href="@Url.Action("Create", "FlowLog")"> 流程修改記錄新增 </a></i></div>
    <table cellpadding="2" class="table" cellspacing="2" border="1">
        <tr class="btn-primary">
            <th> Id</th>
            <th> 修改前內容</th>
            <th> 修改後內容</th> 
            <th> 建立者</th>           
            <th> 建立時間</th>
            <th> </th>
        </tr>
        @if (ViewBag.ListClients != null)
            {
                foreach (var item in ViewBag.ListClients)
                {
                <tr class="btn-xs">
                    <td>@item.Id</td>
                    <td>@item.BeforContent</td>
                    <td>@item.AfterContent</td>
                    <td>@item.Creator</td>
                    <td>@item.CreatedDate.ToString()</td>
                    <td>
                        <i class="fa fa-trash-o" aria-hidden="true"><a onclick="return confirm('Do you want to Delete?')" href="@Url.Action("Delete", "FlowLog", new { id = item.Id })"> 刪除 </a></i>
                        &nbsp;||&nbsp; <i class="fa fa-pencil" aria-hidden="true"><a href="@Url.Action("Edit", "FlowLog", new { id = item.Id })"> 修改 </a></i>
                        &nbsp;|| &nbsp;<i class="fa fa-info" aria-hidden="true"><a href="@Url.Action("Detail", "FlowLog", new { id = item.Id })"> 檢視 </a></i>
                    </td>
                </tr>
            }
        }
    </table>
</div>