UniPsg.Web.UI.PAS/Controllers/AssessCategoryController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;
using UniPsg.Model.PAS.ViewModels;
using UniPsg.Web.UI.PAS.Models;
using PagedList;

namespace UniPsg.Web.UI.PAS.Controllers
{
    public class AssessCategoryController : Controller
    {
        // 分頁後每頁顯示的筆數
        private const int PageSize = 100;
        private AssessCategoryClient client = new AssessCategoryClient();

        // GET: AssessCategory
        public ActionResult Index(string sortOrder, int? page)
        {
            var model = client.FindAll();

            AssessCategoryIndexView viewModel = new AssessCategoryIndexView();                                  

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            switch (sortOrder)
            {
                case "name_desc":
                    model = model.OrderByDescending(m => m.Name);
                    break;
                case "Date":
                    model = model.OrderBy(m => m.ModifiedDate);
                    break;
                case "date_desc":
                    model = model.OrderByDescending(m => m.ModifiedDate);
                    break;
                default:
                    model = model.OrderBy(m => m.Id);
                    break;
            }

            int pageIndex = (page ?? 1);
            viewModel.Categories = model.ToPagedList(pageIndex, PageSize);

            return View(viewModel);
        }
        
        // GET: AssessCategory/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: AssessCategory/Create    
        [HttpPost]
        public ActionResult Create(AssessCategoryViewModel models)
        {
            AssessCategoryClient client = new AssessCategoryClient();
            client.Create(models);
            return RedirectToAction("Index");
        }


        // GET: AssessCategory/Edit/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Edit(int id)
        {   
            AssessCategoryViewModel models = new AssessCategoryViewModel();
            models = client.Find(id);
            return View("Edit", models);            
        }

        //// GET: AssessCategory/Details/5  
        //[AcceptVerbs(HttpVerbs.Get)]
        //public ActionResult Details(int id)
        //{
        //    AssessCategoryViewModel ac = new AssessCategoryViewModel();
        //    ac = client.Find(id);
        //    return View("Details", ac);
        //}

        // GET: AssessCategory/Edit/5    
        [HttpPost]
        public ActionResult Edit(AssessCategoryViewModel models)
        {
            client.Edit(models);
            return RedirectToAction("Index");
        }

        // GET: AssessCategory/Delete/5    
        public ActionResult Delete(int id)
        {
            client.Delete(id);
            return RedirectToAction("Index");
        }

        // GET: AssessCategory/Detail/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Detail(int id)
        {
            AssessCategoryViewModel models = new AssessCategoryViewModel();
            models = client.Find(id);
            return View("Detail", models);
        }


    }
}

UniPsg.Web.UI.PAS/Views/AssessCategory/Create.cshtml
@model UniPsg.Model.PAS.ViewModels.AssessCategoryViewModel
@{
    ViewBag.Title = "考核類別新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5><i class="fa fa-cog" aria-hidden="true">設定管理</i> &nbsp;&gt;&nbsp; <a href="@Url.Action("Index","AssessCategory")">考核類別</a>  &nbsp;&gt;&nbsp; 考核類別新增 </h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <hr />
    @using (Html.BeginForm("Create", "AssessCategory", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*<div class="form-group">
            @Html.LabelFor(m => m.Id, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.Id, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Id, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(m => m.Status, new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.DropDownListFor(m => m.Status, new SelectList(
                      new List<Object>{
                           new { value = 0 , text = "啟用" },
                           new { value = 1 , text = "停用" }},
                      "value", "text",0), "請選擇", new { @class = "form-control" })
                    <br />
                    註：0為啟用、1為停用。
                    @Html.ValidationMessageFor(m => m.Status, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(m => m.Definition, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextAreaFor(m => m.Definition, new { @class = "form-control", @rows = "6", @Value = "" })
                @Html.ValidationMessageFor(m => m.Definition, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(m => m.Creator, new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.TextBoxFor(m => m.Creator, new { @class = "form-control", @Value = @User.Identity.Name, @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.Creator, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @*<div class="form-group">
                @Html.LabelFor(m => m.Modifier, new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.TextBoxFor(m => m.Modifier, new { @class = "form-control", @Value = @User.Identity.Name, @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.Modifier, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="~/AssessCategory" class="btn btn-warning">不儲存退出</a>
                <input type="submit" value="儲存" class="btn btn-success" />
                @Html.HiddenFor(m => m.Status, new { @Value = 0 })
                @Html.HiddenFor(m => m.Creator, new { @Value = @User.Identity.Name })
                @Html.HiddenFor(m => m.Modifier, new { @Value = @User.Identity.Name })                
            </div>
        </div>
    }
</div>

UniPsg.Web.UI.PAS/Views/AssessCategory/Detail.cshtml
@model UniPsg.Model.PAS.ViewModels.AssessCategoryViewModel

@{
    ViewBag.Title = "考核類別檢視";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5><i class="fa fa-cog" aria-hidden="true"> &nbsp;設定管理</i>  &nbsp;&gt;&nbsp;<a href="@Url.Action("Index","AssessCategory")">考核類別</a>  &nbsp;&gt;&nbsp; 考核類別檢視 </h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)           
            <br />
            (註：0為啟用、1為停用。)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Definition)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Definition)
        </dd>
    </dl>
</div>
<div class="btn-sm">
    @Html.DisplayNameFor(m => m.CreatedDate)@Html.DisplayFor(m => m.CreatedDate)，@Html.DisplayNameFor(m => m.Creator) @Html.DisplayFor(m => m.Creator)
    <br />
    @Html.DisplayNameFor(m => m.ModifiedDate)@Html.DisplayFor(m => m.ModifiedDate)，@Html.DisplayNameFor(m => m.Modifier) @Html.DisplayFor(m => m.Modifier)
</div>
<p>
    <i class="fa fa-plus" aria-hidden="true">&nbsp;@Html.ActionLink("新增", "Create", "AssessCategory")</i> | 
    <i class="fa fa-trash-o" aria-hidden="true"><a onclick="return confirm('Do you want to Delete?')" href="@Url.Action("Delete", "AssessCategory", new { id = Model.Id })"> 刪除 </a></i> | 
    <i class="fa fa-pencil" aria-hidden="true">&nbsp;@Html.ActionLink("修改", "Edit", new { id = Model.Id }) </i>|
    <i class="fa fa-list" aria-hidden="true">@Html.ActionLink("Back to List", "Index")</i>
</p>

UniPsg.Web.UI.PAS/Views/AssessCategory/Edit.cshtml
@model UniPsg.Model.PAS.ViewModels.AssessCategoryViewModel
@{
    ViewBag.Title = "考核類別修改";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5><i class="fa fa-cog" aria-hidden="true"> &nbsp;設定管理</i>  &nbsp;&gt;&nbsp;<a href="@Url.Action("Index","AssessCategory")">考核類別</a>  &nbsp;&gt;&nbsp; 考核類別修改 </h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <hr />
    @using (Html.BeginForm("Edit", "AssessCategory", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownListFor(m => m.Status, new SelectList(
                  new List<Object>{
                       new { value = 0 , text = "啟用" },
                       new { value = 1 , text = "停用" }},
                  "value", "text"), "請選擇", new { @class = "form-control" })
                <br />
                註：0為啟用、1為停用。
                @Html.ValidationMessageFor(m => m.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Definition, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextAreaFor(m => m.Definition, new { @class = "form-control", @rows = "6" })
                @Html.ValidationMessageFor(m => m.Definition, "", new { @class = "text-danger" })
            </div>
        </div>       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="~/AssessCategory" class="btn btn-warning">不儲存退出</a>
                <input type="submit" value="儲存" class="btn btn-success" />
                @Html.HiddenFor(m => m.Id)
                @Html.HiddenFor(m => m.Modifier, new { @Value = @User.Identity.Name })                
            </div>
        </div>
    }
</div>

UniPsg.Web.UI.PAS/Views/AssessCategory/Index.cshtml
@using PagedList.Mvc;
@model UniPsg.Web.UI.PAS.Models.AssessCategoryIndexView

@{
    ViewBag.Title = "考核類別清單";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5><i class="fa fa-cog" aria-hidden="true"> &nbsp;設定管理</i> &nbsp;&gt;&nbsp;<a href="@Url.Action("Index","AssessCategory")">考核類別</a></h5>
<center>
    <h4>@ViewBag.Title</h4>
</center>
<div class="form-horizontal">
    <div align="left">
        <i class="fa fa-plus" aria-hidden="true"><a href="@Url.Action("Create","AssessCategory")">&nbsp;考核類別新增 </a></i>
    </div>
    <table cellpadding="2" class="table" cellspacing="2" border="1">
        <tr class="bg-primary">
            <th class="text-nowrap"> Id </th>
            <th class="text-nowrap"> @Html.ActionLink("名稱", "Index", new { sortOrder = ViewBag.NameSortParm }, new { @class = "label label-primary" }) </th>
            <th class="text-nowrap"> 狀 態 </th>
            <th class="text-nowrap"> @Html.ActionLink("修改時間", "Index", new { sortOrder = ViewBag.DateSortParm }, new { @class = "label label-primary" }) </th>
            <th class="text-nowrap"> </th>
        </tr>
        @if (Model.Categories != null)
            {
                foreach (var item in Model.Categories)
                {
                <tr class="btn-sm">
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@Helpers.GetStatusDisplayName(@item.Status)</td>
                    <td>@item.ModifiedDate.ToString()</td>
                    <td align="center" width="15%">
                        <i class="fa fa-trash-o" aria-hidden="true"><a onclick="return confirm('Do you want to Delete?')" href="@Url.Action("Delete", "AssessCategory", new { id = item.Id })"> 刪除 </a></i>
                        &nbsp;||&nbsp;
                        <i class="fa fa-pencil" aria-hidden="true"><a href="@Url.Action("Edit", "AssessCategory", new { id = item.Id })"> 修改 </a></i>
                        &nbsp;|| &nbsp;
                        <i class="fa fa-info" aria-hidden="true"><a href="@Url.Action("Detail", "AssessCategory", new { id = item.Id })"> 檢視 </a></i>
                    </td>
                </tr>
            }
        }
    </table>
    <div class="pager">
        @Html.PagedListPager(Model.Categories, page => Url.Action("Index", new { page }))
    </div>
</div>