UniPsg.Web.UI.PAS/Controllers/MenuController.cs
using System.Web.Mvc;
using UniPsg.Model.PAS.ViewModels;
using UniPsg.Web.UI.PAS.Models;

namespace UniPsg.Web.UI.PAS.Controllers
{
    public class MenuController : Controller
    {
        [Authorize]
        // GET: Menu
        public ActionResult Index()
        {
            MenuClient client = new MenuClient();
            ViewBag.ListClients = client.FindAll();
            return View();
        }
        // GET: Menu/Create
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: Menu/Create    
        [HttpPost]
        public ActionResult Create(MenuViewModel models)
        {
            MenuClient client = new MenuClient();
            client.Create(models);
            return RedirectToAction("Index");
        }


        // GET: Menu/Edit/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Edit(int id)
        {
            MenuClient client = new MenuClient();
            MenuViewModel models = new MenuViewModel();
            models = client.Find(id);
            return View("Edit", models);
        }

        // GET: Menu/Edit/5    
        [HttpPost]
        public ActionResult Edit(MenuViewModel models)
        {
            MenuClient client = new MenuClient();
            client.Edit(models);
            return RedirectToAction("Index");
        }

        // GET: Menu/Delete/5    
        public ActionResult Delete(int id)
        {
            MenuClient client = new MenuClient();
            client.Delete(id);
            return RedirectToAction("Index");
        }


        // GET: Menu/Detail/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Detail(int id)
        {
            MenuClient client = new MenuClient();

            MenuViewModel models = new MenuViewModel();
            models = client.Find(id);
            return View("Detail", models);
        }
    }
}

UniPsg.Web.UI.PAS/Controllers/OrganizationController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UniPsg.Model.PAS.ViewModels;
using UniPsg.Web.UI.PAS.Models;
using PagedList;
using UniPsg.Web.UI.PAS;

namespace UniPsg.Web.UI.PAS.Controllers
{
    public class OrganizationController : Controller
    {
        // 分頁後每頁顯示的筆數
        private const int PageSize = 100;

        private OrganizationClient client = new OrganizationClient();
        private AssessProjectClient projectClient = new AssessProjectClient();
        private AssessPersonClient prnclient = new AssessPersonClient();

        // GET: Organization
        public ActionResult Index(int? projectId, string branchCode, string deptCode, string employee, string sortOrder, int? page)
        {
            var models = client.FindAll();
            ViewBag.Projects = projectClient.FindAll();
            ViewBag.Branches = client.FindBraches();
            ViewBag.Depts = client.FindDepartments();

            OrganizationIndexView viewModel = new OrganizationIndexView();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.BrachSortParm = sortOrder == "Brach" ? "brach_desc" : "Brach";
            ViewBag.DeptSortParm = sortOrder == "Dept" ? "dept_desc" : "Dept";

            if (projectId != null)
            {
                models = models.Where(p => p.ProjectId == projectId);
                ViewBag.CurrentProjectId = projectId;
            }
            if ((!string.IsNullOrWhiteSpace(branchCode)))
            {
                models = models.Where(p => p.BranchCode == branchCode);
                ViewBag.CurrentBranchCode = branchCode;
            }

            if ((!string.IsNullOrWhiteSpace(deptCode)))
            {
                models = models.Where(p => p.DeptCode == deptCode);
                ViewBag.CurrentDeptCode = deptCode;
            }

            if ((!string.IsNullOrWhiteSpace(employee)))
            {
                models = models.Where(p => p.EmployeeNo == employee);                
            }

            switch (sortOrder)
            {
                case "name_desc":
                    models = models.OrderByDescending(m => m.EmployeeNo);
                    break;
                case "Date":
                    models = models.OrderBy(m => m.ModifiedDate);
                    break;
                case "date_desc":
                    models = models.OrderByDescending(m => m.ModifiedDate);
                    break;
                case "Brach":
                    models = models.OrderBy(m => m.BranchName);
                    break;
                case "brach_desc":
                    models = models.OrderByDescending(m => m.BranchName);
                    break;
                case "Dept":
                    models = models.OrderBy(m => m.DeptCode);
                    break;
                case "dept_desc":
                    models = models.OrderByDescending(m => m.DeptCode);
                    break;                
                default:
                    models = models.OrderBy(m => m.ProjectId);
                    break;
            }

            int pageIndex = (page ?? 1);
            viewModel.Organizations = models.ToPagedList(pageIndex, PageSize);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(OrganizationIndexView vm, string sortOrder, int? page)
        {
            var model = client.FindAll();
            ViewBag.Projects = projectClient.FindAll();
            ViewBag.Branches = client.FindBraches();
            ViewBag.Depts = client.FindDepartments();

            OrganizationIndexView viewModel = new OrganizationIndexView();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.BrachSortParm = sortOrder == "Brach" ? "brach_desc" : "Brach";
            ViewBag.DeptSortParm = sortOrder == "Dept" ? "dept_desc" : "Dept";

            if (vm.ProjectId > 0)
            {
                model = model.Where(p => p.ProjectId == vm.ProjectId);
                ViewBag.CurrentProjectId = vm.ProjectId;
            }
            if ((!string.IsNullOrWhiteSpace(vm.BranchCode)))
            {
                model = model.Where(p => p.BranchCode == vm.BranchCode);
                ViewBag.CurrentBranchCode = vm.BranchCode;
            }

            if ((!string.IsNullOrWhiteSpace(vm.DeptCode)))
            {
                model = model.Where(p => p.DeptCode == vm.DeptCode);
                ViewBag.CurrentDeptCode = vm.DeptCode;
            }

            if ((!string.IsNullOrWhiteSpace(vm.EmployeeNo)))
            {
                model = model.Where(p => p.EmployeeNo == vm.EmployeeNo);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    model = model.OrderByDescending(m => m.EmployeeNo);
                    break;
                case "Date":
                    model = model.OrderBy(m => m.ModifiedDate);
                    break;
                case "date_desc":
                    model = model.OrderByDescending(m => m.ModifiedDate);
                    break;
                case "Brach":
                    model = model.OrderBy(m => m.BranchName);
                    break;
                case "brach_desc":
                    model = model.OrderByDescending(m => m.BranchName);
                    break;
                case "Dept":
                    model = model.OrderBy(m => m.DeptCode);
                    break;
                case "dept_desc":
                    model = model.OrderByDescending(m => m.DeptCode);
                    break;               
                default:
                    model = model.OrderBy(m => m.ProjectId);
                    break;
            }
            int pageIndex = (page ?? 1);

            viewModel.Organizations = model.ToPagedList(pageIndex, PageSize);

            return View(viewModel);
        }
        // GET: Organization/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Projects = projectClient.FindByStatus(0);
            return View("Create");
        }

        // POST: Organization/Create    
        [HttpPost]
        public ActionResult Create(OrganizationViewModel models)
        {
            client.Create(models);
            return RedirectToAction("Index");
        }


        // GET: Organization/Edit/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Edit(int projectId, string employeeNo)
        {
            ViewBag.Projects = projectClient.FindByStatus(0);
            OrganizationViewModel models = new OrganizationViewModel();
            models = client.Find(projectId, employeeNo);
            return View("Edit", models);
        }
        

        // GET: Organization/Edit/5    
        [HttpPost]
        public ActionResult Edit(OrganizationViewModel models)
        {
            client.Edit(models);
            return RedirectToAction("Index");
        }

        // GET: Organization/Delete/5    
        public ActionResult Delete(int projectId, string employeeNo)
        {
            client.Delete(projectId, employeeNo);
            return RedirectToAction("Index");
        }

        // GET: Organization/Detail/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Detail(int projectId, string employeeNo)
        {
            OrganizationViewModel models = new OrganizationViewModel();
            models = client.Find(projectId, employeeNo);
            return View("Detail", models);
        }

        // GET: Organization/Imports/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Imports(int projectId)
        {
            var project = projectClient.Find(projectId);
            ViewBag.ProjectId = project.Id;
            ViewBag.ProjectName = project.Name;
            ViewBag.Rows = prnclient.FindByProjectId(projectId);
            return View("Imports");
        }

        // GET: Organization/Imports/5    
        [HttpPost]
        public ActionResult Imports(OrganizationImportModel model)
        {
            client.Imposts(model);
            return RedirectToAction("Index", "AssessProject");
        }

        // GET: Organization/Flow/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Flow(int projectId, string employeeNo)
        {
            ViewBag.Projects = projectClient.FindByStatus(0);
            ViewBag.ProjectId = projectId;
            OrganizationViewModel models = new OrganizationViewModel();
            models = client.Find(projectId, employeeNo);
            return View("Flow", models);
        }


        // GET: Organization/Flow/5    
        [HttpPost]
        public ActionResult Flow(OrganizationViewModel models)
        {
            int projectId = models.ProjectId;
            client.Edit(models);
            return RedirectToAction("List", "AssessPerson", new { projectId = projectId});
        }

        // GET: Organization/Account/5  
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Account(int projectId, string employeeNo)
        {
            ViewBag.Projects = projectClient.FindByStatus(0);
            ViewBag.ProjectId = projectId;
            OrganizationViewModel models = new OrganizationViewModel();
            models = client.Find(projectId, employeeNo);
            return View("Account", models);
        }


        // GET: Organization/Flow/5    
        [HttpPost]
        public ActionResult Account(OrganizationViewModel models)
        {
            int projectId = models.ProjectId;
            client.Edit(models);
            return RedirectToAction("Index");
        }


    }
}

UniPsg.Web.UI.PAS/Views/Organization/Account.cshtml
@using UniPsg.Web.UI.PAS.Utility.Enums
@model UniPsg.Model.PAS.ViewModels.OrganizationViewModel

@{
    ViewBag.Title = "上層主管修改";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h5><i class="fa fa-cog" aria-hidden="true"> &nbsp;設定管理</i>  &nbsp;&gt;&nbsp; <a href="@Url.Action("Index","Organization")">組織流程</a> &nbsp;&gt;&nbsp; 上層主管修改 </h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <hr />
    @using (Html.BeginForm("Account", "Organization", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.EmployeeNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.EmployeeNo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(m => m.EmployeeNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.EmployeeName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(m => m.EmployeeName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ManagerNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.ManagerNo, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(m => m.ManagerNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="~/Organization" class="btn btn-warning">不儲存退出</a>
                <input type="submit" value="儲存" class="btn btn-success" />
                @Html.HiddenFor(m => m.ProjectId)               
                @Html.HiddenFor(m => m.Modifier, new { @Value = @User.Identity.Name })
                @Html.HiddenFor(m => m.ProjectName)               
                @Html.HiddenFor(m => m.NamePath)
                @Html.HiddenFor(m => m.FlowPath)
                @Html.HiddenFor(m => m.BranchCode)
                @Html.HiddenFor(m => m.BranchName)
                @Html.HiddenFor(m => m.DeptCode)
                @Html.HiddenFor(m => m.DeptName)
                @Html.HiddenFor(m => m.TeamCode)
                @Html.HiddenFor(m => m.TeamName)
                @Html.HiddenFor(m => m.Account)
                @Html.HiddenFor(m => m.ManageName)
                @Html.HiddenFor(m => m.ManageAccount)
                @Html.HiddenFor(m => m.Status)
            </div>
        </div>
    }
</div>

@*<script>
        $(document).ready(function () {
            $("#ViewStarDate").datepicker({
                dateFormat: "yymmdd"
            });
        });
    </script>*@

UniPsg.Web.UI.PAS/Views/Organization/Create.cshtml
@model UniPsg.Model.PAS.ViewModels.OrganizationViewModel

@{
    ViewBag.Title = "人員組織新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h5><i class="fa fa-cog" aria-hidden="true"> &nbsp;設定管理</i>  &nbsp;&gt;&nbsp; <a href="@Url.Action("Index","Organization")">人員組織</a>  &nbsp;&gt;&nbsp;人員組織新增 </h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <hr />
    @using (Html.BeginForm("Create", "Organization", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.ProjectId, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownListFor(m => m.ProjectId, new SelectList(ViewBag.Projects, "Id", "Name"), "請選擇", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.EmployeeNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeNo, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BranchCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.BranchCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BranchCode, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.EditorFor(model => model.BranchName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BranchName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DeptCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.DeptCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeptCode, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.EditorFor(model => model.DeptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeptName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TeamCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.TeamCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamCode, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.EditorFor(model => model.TeamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ManagerNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.ManagerNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerNo, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.EditorFor(model => model.ManageName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManageName, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.EditorFor(model => model.ManageAccount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManageAccount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.FlowPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(m => m.FlowPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.FlowPath, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.EditorFor(m => m.NamePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.NamePath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="~/Organization" class="btn btn-warning">不儲存退出</a>
                <input type="submit" value="儲存" class="btn btn-success" />
                @Html.HiddenFor(m => m.Status, new { @Value = 0 })
                @Html.HiddenFor(m => m.Creator, new { @Value = @User.Identity.Name })
                @Html.HiddenFor(m => m.Modifier, new { @Value = @User.Identity.Name })                
            </div>
        </div>
    }
</div>

UniPsg.Web.UI.PAS/Views/Organization/Detail.cshtml
@model UniPsg.Model.PAS.ViewModels.OrganizationViewModel

@{
    ViewBag.Title = "選單檢視";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5>權限設定  &nbsp;&gt;&nbsp;<a href="@Url.Action("Index","Menu")">選單</a>  &nbsp;&gt;&nbsp; 選單檢視 </h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BranchCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BranchCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BranchName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BranchName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeptCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeptCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeptName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeamCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManageAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManageAccount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlowPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlowPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
            <br />
            (註：0為啟用、1為停用。)
        </dd>
    </dl>
</div>
<div class="btn-sm">
    @Html.DisplayNameFor(m => m.CreatedDate)@Html.DisplayFor(m => m.CreatedDate)，@Html.DisplayNameFor(m => m.Creator) @Html.DisplayFor(m => m.Creator)
    <br />
    @Html.DisplayNameFor(m => m.ModifiedDate)@Html.DisplayFor(m => m.ModifiedDate)，@Html.DisplayNameFor(m => m.Modifier) @Html.DisplayFor(m => m.Modifier)
</div>
<p>
    <i class="fa fa-plus" aria-hidden="true">&nbsp;@Html.ActionLink("新增", "Create", "Organization")</i> |
    <i class="fa fa-trash-o" aria-hidden="true"><a onclick="return confirm('Do you want to Delete?')" href="@Url.Action("Delete", "Organization", new { projectId = Model.ProjectId, employeeNo = Model.EmployeeNo })"> 刪除 </a></i> |
    <i class="fa fa-pencil" aria-hidden="true">&nbsp;@Html.ActionLink("修改", "Edit", new { projectId = Model.ProjectId, employeeNo = Model.EmployeeNo }) </i>|
    <i class="fa fa-list" aria-hidden="true">@Html.ActionLink("Back to List", "Index")</i>
</p>

UniPsg.Web.UI.PAS/Views/Organization/Flow.cshtml
@using UniPsg.Web.UI.PAS.Utility.Enums
@model UniPsg.Model.PAS.ViewModels.OrganizationViewModel

@{
    ViewBag.Title = "人員流程修改";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h5><i class="fa fa-cog" aria-hidden="true"> &nbsp;設定管理</i>  &nbsp;&gt;&nbsp; <a href="@Url.Action("Index","AssessProject")">考核專案</a> &nbsp;&gt;&nbsp; 人員流程流程修改 </h5>
<center><h4>@ViewBag.Title</h4></center>
<div class="form-horizontal">
    <hr />
    @using (Html.BeginForm("Flow", "Organization", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.FlowPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.FlowPath, new { htmlAttributes = new { @class = "form-control", @rows = "6" } })
                <br/>
                例如: 01012,84182,87188,87161 為完整的輸入流程。
                @Html.ValidationMessageFor(m => m.FlowPath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.FlowPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.NamePath, new { @class = "form-control", @rows = "6" })
                <br/>
                例如: 吳淑娟(01012),林慶瑞(84182),胡懿德(87188),林榮輝(87161) 為完整的輸入流程。
                @Html.ValidationMessageFor(m => m.NamePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="~/AssessPerson/List?projectId=@ViewBag.ProjectId" class="btn btn-warning">不儲存退出</a>
                <input type="submit" value="儲存" class="btn btn-success" />
                @Html.HiddenFor(m => m.ProjectId)
                @Html.HiddenFor(m => m.EmployeeNo)
                @Html.HiddenFor(m => m.EmployeeName)               
                @Html.HiddenFor(m => m.ProjectName)               
                @Html.HiddenFor(m => m.Account)
                @Html.HiddenFor(m => m.BranchCode)
                @Html.HiddenFor(m => m.BranchName)
                @Html.HiddenFor(m => m.DeptCode)
                @Html.HiddenFor(m => m.DeptName)
                @Html.HiddenFor(m => m.TeamCode)
                @Html.HiddenFor(m => m.TeamName)
                @Html.HiddenFor(m => m.ManagerNo)
                @Html.HiddenFor(m => m.ManageName)
                @Html.HiddenFor(m => m.ManageAccount)
                @Html.HiddenFor(m => m.Status)
                @Html.HiddenFor(m => m.Modifier, new { @Value = @User.Identity.Name })
            </div>
        </div>
    }
</div>

@*<script>
        $(document).ready(function () {
            $("#ViewStarDate").datepicker({
                dateFormat: "yymmdd"
            });
        });
    </script>*@