UniPsg.Web.UI.PAS/Controllers/PerformanceController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UniPsg.Web.UI.PAS.Models;
using PagedList;
using System.Data.Linq.SqlClient;
using UniPsg.Model.PAS.ViewModels;
using System.DirectoryServices;

namespace UniPsg.Web.UI.PAS.Controllers
{
    public class PerformanceController : Controller
    {
        // 分頁後每頁顯示的筆數
        private const int PageSize = 100;
        private string LDAPPath = System.Web.Configuration.WebConfigurationManager.AppSettings["LDAPPath"];

        private AssessPersonClient client = new AssessPersonClient();
        private AssessGroupClient groupClient = new AssessGroupClient();
        private AssessProjectClient projectClient = new AssessProjectClient();
        private AssessFormClient formClient = new AssessFormClient();
        private OrganizationClient orgClient = new OrganizationClient();
        private RoleUserMappingClient ruClient = new RoleUserMappingClient();
        private ManagerClient mangeClient = new ManagerClient();
        private ScopeItemClient itemeClient = new ScopeItemClient();

        // GET: AssessPerson        
        //public ActionResult Index(int projectId,string sortOrder, string searchString, int? page)
        public ActionResult Index(int? projectId, string branchCode, string deptCode, string sortOrder, int? page)
        {

            var model = client.FindAll();

            // 1.取得員編
            string account = User.Identity.Name.ToString();
            //string account = @"PSCNET\79338";
            //string account = @"PSCNET\ALEN";
            //string account = @"PSCNET\CHEEKO.WU";
            //string account = @"PSCNET\KAVIN";            
            //string account = @"PSCNET\james";
            account = account.Replace(@"labpsc\", "");
            account = account.Replace(@"LABPSC\", "");
            account = account.Replace(@"pscnet\", "");
            account = account.Replace(@"PSCNET\", "");
            //var employeeNo = orgClient.FindEmployeeNumber(account, 0);
            string employeeNo = string.Empty;
            //var employeeNo = orgClient.FindEmployeeNumber(account, 0);
            DirectoryEntry searchRoot = new DirectoryEntry(LDAPPath);
            DirectorySearcher search = new DirectorySearcher(searchRoot);
            search.Filter = "(&(objectClass=user)(SAMAccountName=" + account.ToUpper() + "))";
            SearchResult results = search.FindOne();
            if (results != null)
            {
                ResultPropertyCollection resultPropColl;
                resultPropColl = results.Properties;
                employeeNo = (string)resultPropColl["description"][0];
            }
            // 2.取得角色            
            model = model.Where(m => m.FlowPath.Contains(employeeNo));
            ViewBag.Projects = projectClient.FindByStatus(0);
            ViewBag.Branches = orgClient.FindBraches();
            ViewBag.Depts = orgClient.FindDepartments();

            ViewBag.Count = model.Count();
            ViewBag.Viewer = employeeNo;

            AssessPersonIndexView viewModel = new AssessPersonIndexView();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.BrachSortParm = sortOrder == "Brach" ? "brach_desc" : "Brach";
            ViewBag.DeptSortParm = sortOrder == "Dept" ? "dept_desc" : "Dept";
            ViewBag.TeamSortParm = sortOrder == "Team" ? "team_desc" : "Team";
            ViewBag.GroupSortParm = sortOrder == "Group" ? "group_desc" : "Group";

            if (projectId != null)
            {
                model = model.Where(p => p.ProjectId == projectId);
                ViewBag.CurrentProjectId = projectId;
            }
            if ((!string.IsNullOrWhiteSpace(branchCode)))
            {
                model = model.Where(p => p.BranchCode == branchCode);
                ViewBag.CurrentBranchCode = branchCode;
            }

            if ((!string.IsNullOrWhiteSpace(deptCode)))
            {
                model = model.Where(p => p.DeptCode == deptCode);
                ViewBag.CurrentDeptCode = deptCode;
            }
            switch (sortOrder)
            {
                case "name_desc":
                    model = model.OrderByDescending(m => m.FormName);
                    break;
                case "Date":
                    model = model.OrderBy(m => m.ModifiedDate);
                    break;
                case "date_desc":
                    model = model.OrderByDescending(m => m.ModifiedDate);
                    break;
                case "Brach":
                    model = model.OrderBy(m => m.BranchName);
                    break;
                case "brach_desc":
                    model = model.OrderByDescending(m => m.BranchName);
                    break;
                case "Dept":
                    model = model.OrderBy(m => m.DeptCode);
                    break;
                case "dept_desc":
                    model = model.OrderByDescending(m => m.DeptCode);
                    break;
                case "Team":
                    model = model.OrderBy(m => m.TeamCode);
                    break;
                case "team_desc":
                    model = model.OrderByDescending(m => m.TeamCode);
                    break;
                case "Group":
                    model = model.OrderBy(m => m.GroupName);
                    break;
                case "group_desc":
                    model = model.OrderByDescending(m => m.GroupName);
                    break;
                default:
                    model = model.OrderBy(m => m.ProjectId);
                    break;
            }
            int pageIndex = (page ?? 1);

            viewModel.People = model.ToPagedList(pageIndex, PageSize);

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Index(AssessPersonIndexView vm, string sortOrder, int? page)
        {
            var model = client.FindAll();
            ViewBag.Projects = projectClient.FindByStatus(0);
            ViewBag.Branches = orgClient.FindBraches();
            ViewBag.Depts = orgClient.FindDepartments();

            AssessPersonIndexView viewModel = new AssessPersonIndexView();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (vm.ProjectId > 0)
            {
                model = model.Where(p => p.ProjectId == vm.ProjectId);
                ViewBag.CurrentProjectId = vm.ProjectId;
            }
            if ((!string.IsNullOrWhiteSpace(vm.BranchCode)))
            {
                model = model.Where(p => p.BranchCode == vm.BranchCode);
                ViewBag.CurrentBranchCode = vm.BranchCode;
            }

            if ((!string.IsNullOrWhiteSpace(vm.DeptCode)))
            {
                model = model.Where(p => p.DeptCode == vm.DeptCode);
                ViewBag.CurrentDeptCode = vm.DeptCode;
            }

            switch (sortOrder)
            {
                case "name_desc":
                    model = model.OrderByDescending(m => m.FormName);
                    break;
                case "Date":
                    model = model.OrderBy(m => m.ModifiedDate);
                    break;
                case "date_desc":
                    model = model.OrderByDescending(m => m.ModifiedDate);
                    break;
                default:
                    model = model.OrderBy(m => m.ProjectId);
                    break;
            }
            int pageIndex = (page ?? 1);

            viewModel.People = model.ToPagedList(pageIndex, PageSize);

            return View(viewModel);
        }

        public ActionResult Detail1(int projectId, string employeeNo)
        {
            var model = mangeClient.FindReviewer(projectId, employeeNo);

            if (model.GroupId == 6)
            {
                ManageUpdateIndexView mv = new ManageUpdateIndexView();
                mv.BranchCode = model.BranchCode;
                mv.BranchName = model.BranchName;
                mv.CategoryId = model.CategoryId;
                mv.DeptCode = model.DeptCode;
                mv.DeptName = model.DeptName;
                mv.Education = model.Education;
                mv.EmployeeName = model.EmployeeName;
                mv.EmployeeNo = model.EmployeeNo;
                mv.FormId = model.FormId;
                mv.FormName = model.FormName;
                mv.GroupId = model.GroupId;
                mv.GroupName = model.GroupName;
                mv.JobCapName = model.JobCapName;
                mv.ProjectId = model.ProjectId;
                mv.ProjectName = model.ProjectName;
                mv.Reviewer = model.Reviewer;
                mv.StartDate = model.StartDate;
                mv.TeamCode = model.TeamCode;
                mv.TeamName = model.TeamName;
                mv.ViewStarDate = model.ViewStarDate;
                mv.ViewEndDate = model.ViewEndDate;
                if (model.Reviews.Count != 0)
                {
                    mv.Reviews1 = model.Reviews.FindAll(r => r.KPICategoryId == 11).OrderBy(r => r.CreatedDate).ToList();
                    mv.Reviews2 = model.Reviews.FindAll(r => r.KPICategoryId == 9).OrderBy(r => r.CreatedDate).ToList();
                    mv.Reviews3 = model.Reviews.FindAll(r => r.KPICategoryId == 12).OrderBy(r => r.CreatedDate).ToList();
                    mv.Reviews4 = model.Reviews.FindAll(r => r.KPICategoryId == 13).OrderBy(r => r.CreatedDate).ToList();
                }
                var item1 = itemeClient.Find(52);
                var item2 = itemeClient.Find(53);
                var item3 = itemeClient.Find(54);
                var item4 = itemeClient.Find(55);

UniPsg.Web.UI.PAS/Views/Performance/Detail14.cshtml
@using UniPsg.Web.UI.PAS.Utility.Enums
@model UniPsg.Model.PAS.ViewModels.ManageUpdateViewModel

@{
    ViewBag.Title = "績效考核檢視";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5><i class="fa fa-line-chart" aria-hidden="true">&nbsp;績效查詢</i>  &nbsp;&gt;&nbsp; <a href="@Url.Action("Index","Performance")">績效進度查詢</a> &nbsp;&gt;&nbsp; 績效考核檢視</h5>
@*<center><h4>@ViewBag.Title</h4></center>*@
<div class="form-horizontal">
    <hr />
    <div class="form-group">
        <div class="col-md-10">
            <center><h4>@Model.ProjectName &nbsp; 【適用對象：@Model.GroupName】</h4></center>
            <center><h5>考核期間：@Helpers.GetShowDate(Model.ViewStarDate)  &nbsp;&nbsp;至&nbsp;&nbsp;@Helpers.GetShowDate(Model.ViewEndDate) </h5></center>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <table cellpadding="2" class="table" cellspacing="2" border="1">
                <tr class="btn-default">
                    <th class="text-nowrap"> 分公司</th>
                    <th class="text-nowrap"> 姓名</th>
                    <th class="text-nowrap"> 職稱</th>
                    <th class="text-nowrap"> 到職日</th>
                </tr>
                <tr class="btn-xs">
                    <td>@Model.BranchName</td>
                    <td>@Model.EmployeeName</td>
                    <td>@Model.JobCapName</td>
                    <td>@Helpers.GetShowDate(Model.StartDate)</td>
                </tr>
            </table>
        </div>
    </div>
    @if (Model.Reviews != null)
    {
        <div class="form-group">
            <div class="col-md-10">
                @Html.Label("Lable1", "I、工作目標達成狀況評核(KPI)：")
            </div>
            <div class="col-md-10">
                <table cellpadding="2" class="table" cellspacing="2" border="1">
                    <tr class="btn-default">
                        <th class="text-nowrap"> 分類 </th>
                        <th class="text-nowrap"> 項目 </th>
                        <th class="text-nowrap"> 比重<br />(%)</th>
                        <th class="text-nowrap"> 執行狀況說明<br />(EX:達成率)</th>
                        <th class="text-nowrap"> 自我檢視<br />工作目標達成或未達成之說明及工作心得與困難之描述</th>
                        <th class="text-nowrap"> 主管檢視<br />工作目標達成之建議及困難之輔助</th>
                    </tr>
                    @for (int i = 0; i < Model.Reviews.Count(); i++)
                    {
                        @Html.HiddenFor(model => model.Reviews[i].Id)
                        @Html.HiddenFor(model => model.Reviews[i].ProjectId)
                        @Html.HiddenFor(model => model.Reviews[i].EmployeeNo)
                        @Html.HiddenFor(model => model.Reviews[i].Reviewer)
                        @Html.HiddenFor(model => model.Reviews[i].ScopeId)
                        @Html.HiddenFor(model => model.Reviews[i].KPICategoryId)
                        @Html.HiddenFor(model => model.Reviews[i].KPICategoryName)
                        @Html.HiddenFor(model => model.Reviews[i].ItemId)
                        @Html.HiddenFor(model => model.Reviews[i].ItemName)
                        @Html.HiddenFor(model => model.Reviews[i].Definition)
                        @Html.HiddenFor(model => model.Reviews[i].Weight)
                        @Html.HiddenFor(model => model.Reviews[i].Rate)
                        @Html.HiddenFor(model => model.Reviews[i].Score)
                        @Html.HiddenFor(model => model.Reviews[i].Comment)
                        @Html.HiddenFor(model => model.Reviews[i].Creator)
                        @Html.HiddenFor(model => model.Reviews[i].Modifier, new { @Value = @User.Identity.Name })

                        <tr class="btn-xs">
                            <td>
                                @Model.Reviews[i].KPICategoryName
                            </td>
                            <td>
                                <u>@Model.Reviews[i].ItemName</u>
                                <br />
                                @Model.Reviews[i].Definition
                            </td>
                            <td>
                                @Model.Reviews[i].Weight
                            </td>
                            <td>
                                @Model.Reviews[i].Rate
                            </td>
                            <td style="white-space: pre-line">
                                @Model.Reviews[i].Comment
                            </td>
                            <td style="white-space: pre-line">
                                @Model.Reviews[i].Comment1
                        </tr>
                    }
                </table>
            </div>
        </div>
    }
    @*//主管評語*@
    <div class="form-group">
        <div class="col-md-10">
            @Html.Label("Lable2", "主管評語：")
        </div>
        @for (int i = 0; i < Model.Scores.Count(); i++)
        {
            <div class="col-md-3">
                @Html.HiddenFor(model => model.Scores[i].Id)
                @Html.HiddenFor(model => model.Scores[i].ProjectId)
                @Html.HiddenFor(model => model.Scores[i].EmployeeNo)
                @Html.HiddenFor(model => model.Scores[i].Reviewer)
                @Html.HiddenFor(model => model.Scores[i].Modifier, new { @Value = @User.Identity.Name })


                <p>@Model.Scores[i].ReviewName (@Model.Scores[i].Reviewer)：</p>
                @Html.TextAreaFor(model => model.Scores[i].Comment, new { @class = "form-control", @Row = 6, @readonly = "readonly" })

            </div>
        }
    </div>
</div>

UniPsg.Web.UI.PAS/Views/Performance/Detail16.cshtml
@using UniPsg.Web.UI.PAS.Utility.Enums
@model UniPsg.Web.UI.PAS.Models.ManageUpdateIndexView

@{
    ViewBag.Title = "績效考核檢視";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5><i class="fa fa-line-chart" aria-hidden="true">&nbsp;績效查詢</i>  &nbsp;&gt;&nbsp; <a href="@Url.Action("Index","Performance")">績效進度查詢</a> &nbsp;&gt;&nbsp; 績效考核檢視</h5>
@*<center><h4>@ViewBag.Title</h4></center>*@
<div class="form-horizontal">
    <hr />
   
        <div class="form-group">
            <div class="col-md-10">
                <center><h5>@Model.ProjectName</h5></center>
                <center><h5>【適用對象：@Model.GroupName】</h5></center>
                <center><h5>考核期間：@Helpers.GetShowDate(Model.ViewStarDate)  &nbsp;&nbsp;至&nbsp;&nbsp;@Helpers.GetShowDate(Model.ViewEndDate) </h5></center>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <table cellpadding="2" class="table" cellspacing="2" border="1">
                    <tr class="btn-default">
                        <th class="text-nowrap"> 部門碼</th>
                        <th class="text-nowrap"> 科組</th>
                        <th class="text-nowrap"> 員工編號</th>
                        <th class="text-nowrap"> 姓名 </th>
                        <th class="text-nowrap"> 到職日 </th>
                        <th class="text-nowrap"> 職稱 </th>
                        <th class="text-nowrap"> 最高學歷 </th>
                    </tr>
                    <tr class="btn-xs">
                        <td>@Model.DeptCode</td>
                        <td>@Model.TeamName</td>
                        <td>@Model.EmployeeNo</td>
                        <td>@Model.EmployeeName</td>
                        <td>@Helpers.GetShowDate(Model.StartDate)</td>
                        <td>@Model.JobCapName</td>
                        <td>@Model.Education</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.Label("Lable1", "I、工作目標達成狀況評核：")<br />
                一、@ViewBag.ScopItem1：&nbsp; <br />
                @ViewBag.Definition1
            </div>
            <div class="col-md-10">
                <table cellpadding="2" class="table" cellspacing="2" border="1">
                    <tr class="btn-default">
                        <th class="text-nowrap"> 工作要項及目標</th>
                        <th class="text-nowrap"> 執行狀況說明(EX:達成率)</th>
                        <th class="text-nowrap"> 自我檢視<br /> 工作目標達成或未達成之說明及工作心得與困難之描述</th>
                        <th class="text-nowrap"> 主管檢視<br />工作目標達成之建議及困難之輔助</th>
                    </tr>
                    @if (Model.Reviews1 != null)
                    {
                        for (int i = 0; i < Model.Reviews1.Count(); i++)
                        {
                            @Html.HiddenFor(model => model.Reviews1[i].Id)
                            @Html.HiddenFor(model => model.Reviews1[i].ProjectId)
                            @Html.HiddenFor(model => model.Reviews1[i].EmployeeNo)
                            @Html.HiddenFor(model => model.Reviews1[i].Reviewer)
                            @Html.HiddenFor(model => model.Reviews1[i].Modifier, new { @Value = @User.Identity.Name })
                            @Html.HiddenFor(model => model.Reviews1[i].ItemId)
                            @Html.HiddenFor(model => model.Reviews1[i].ItemName)
                            @Html.HiddenFor(model => model.Reviews1[i].Rate)
                            @Html.HiddenFor(model => model.Reviews1[i].Comment)
                            <tr class="btn-sm">
                                <td>@Model.Reviews1[i].ItemName</td>
                                <td>@Model.Reviews1[i].Rate</td>
                                <td style="white-space: pre-line">@Model.Reviews1[i].Comment</td>
                                <td style="white-space: pre-line">
                                        @Model.Reviews1[i].Comment1                                   
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @*@Html.Label("Lable2", "二、人員管理能力暨內部流程改善：") &nbsp;*@
                二、@ViewBag.ScopItem2：&nbsp;                <br />
                @ViewBag.Definition2
            </div>
            <div class="col-md-10">
                <table cellpadding="2" class="table" cellspacing="2" border="1">
                    <tr class="btn-default">
                        <th class="text-nowrap"> 工作要項及目標</th>
                        <th class="text-nowrap"> 執行狀況說明(EX:達成率)</th>
                        <th class="text-nowrap"> 自我檢視<br /> 工作目標達成或未達成之說明及工作心得與困難之描述</th>
                        <th class="text-nowrap"> 主管檢視<br />工作目標達成之建議及困難之輔助</th>
                    </tr>
                    @if (Model.Reviews2 != null)
                    {
                        for (int i = 0; i < Model.Reviews2.Count(); i++)
                        {
                            @Html.HiddenFor(model => model.Reviews2[i].Id)
                            @Html.HiddenFor(model => model.Reviews2[i].ProjectId)
                            @Html.HiddenFor(model => model.Reviews2[i].EmployeeNo)
                            @Html.HiddenFor(model => model.Reviews2[i].Reviewer)
                            @Html.HiddenFor(model => model.Reviews2[i].Modifier, new { @Value = @User.Identity.Name })
                            @Html.HiddenFor(model => model.Reviews2[i].ItemId)
                            @Html.HiddenFor(model => model.Reviews2[i].ItemName)
                            @Html.HiddenFor(model => model.Reviews2[i].Rate)
                            @Html.HiddenFor(model => model.Reviews2[i].Comment)
                            <tr class="btn-sm">
                                <td>@Model.Reviews2[i].ItemName</td>
                                <td>@Model.Reviews2[i].Rate</td>
                                <td style="white-space: pre-line">@Model.Reviews2[i].Comment</td>
                                <td style="white-space: pre-line">                                   
                                        @Model.Reviews2[i].Comment1                                   
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                三、@ViewBag.ScopItem3：&nbsp;               <br />
                @ViewBag.Definition3
            </div>
            <div class="col-md-10">
                <table cellpadding="2" class="table" cellspacing="2" border="1">
                    <tr class="btn-default">
                        <th class="text-nowrap"> 工作要項及目標</th>
                        <th class="text-nowrap"> 執行狀況說明(EX:達成率)</th>
                        <th class="text-nowrap"> 自我檢視<br /> 工作目標達成或未達成之說明及工作心得與困難之描述</th>
                        <th class="text-nowrap"> 主管檢視<br />工作目標達成之建議及困難之輔助</th>
                    </tr>
                    @if (Model.Reviews3 != null)
                    {
                        for (int i = 0; i < Model.Reviews3.Count(); i++)
                        {
                            @Html.HiddenFor(model => model.Reviews3[i].Id)
                            @Html.HiddenFor(model => model.Reviews3[i].ProjectId)
                            @Html.HiddenFor(model => model.Reviews3[i].EmployeeNo)
                            @Html.HiddenFor(model => model.Reviews3[i].Reviewer)
                            @Html.HiddenFor(model => model.Reviews3[i].Modifier, new { @Value = @User.Identity.Name })
                            @Html.HiddenFor(model => model.Reviews3[i].ItemId)
                            @Html.HiddenFor(model => model.Reviews3[i].ItemName)
                            @Html.HiddenFor(model => model.Reviews3[i].Rate)
                            @Html.HiddenFor(model => model.Reviews3[i].Comment)
                            <tr class="btn-sm">
                                <td>@Model.Reviews3[i].ItemName</td>
                                <td>@Model.Reviews3[i].Rate</td>
                                <td style="white-space: pre-line">@Model.Reviews3[i].Comment</td>
                                <td style="white-space: pre-line">
                                   
                                        @Model.Reviews3[i].Comment1
                                   
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                四、@ViewBag.ScopItem4：&nbsp;
            </div>
            <div class="col-md-10">
                <table cellpadding="2" class="table" cellspacing="2" border="1">
                    <tr class="btn-default">
                        <th class="text-nowrap"> 工作要項及目標</th>
                        <th class="text-nowrap"> 執行狀況說明(EX:達成率)</th>
                        <th class="text-nowrap"> 自我檢視<br /> 工作目標達成或未達成之說明及工作心得與困難之描述</th>
                        <th class="text-nowrap"> 主管檢視<br />工作目標達成之建議及困難之輔助</th>
                    </tr>
                    @if (Model.Reviews4 != null)
                    {
                        for (int i = 0; i < Model.Reviews4.Count(); i++)
                        {
                            @Html.HiddenFor(model => model.Reviews4[i].Id)
                            @Html.HiddenFor(model => model.Reviews4[i].ProjectId)
                            @Html.HiddenFor(model => model.Reviews4[i].EmployeeNo)
                            @Html.HiddenFor(model => model.Reviews4[i].Reviewer)
                            @Html.HiddenFor(model => model.Reviews4[i].Modifier, new { @Value = @User.Identity.Name })
                            @Html.HiddenFor(model => model.Reviews4[i].ItemId)
                            @Html.HiddenFor(model => model.Reviews4[i].ItemName)
                            @Html.HiddenFor(model => model.Reviews4[i].Rate)
                            @Html.HiddenFor(model => model.Reviews4[i].Comment)
                            <tr class="btn-sm">
                                <td>@Model.Reviews4[i].ItemName</td>
                                <td>@Model.Reviews4[i].Rate</td>
                                <td style="white-space: pre-line">@Model.Reviews4[i].Comment</td>
                                <td style="white-space: pre-line">
                                        @Model.Reviews4[i].Comment1                                    
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>

        @*//主管評語*@
        <div class="form-group">
            <div class="col-md-10">
                @Html.Label("Lable2", "主管評語：")
            </div>


            @for (int i = 0; i < Model.Scores.Count(); i++)
                {
                <div class="col-md-3">
                    @Html.HiddenFor(model => model.Scores[i].Id)
                    @Html.HiddenFor(model => model.Scores[i].ProjectId)
                    @Html.HiddenFor(model => model.Scores[i].EmployeeNo)
                    @Html.HiddenFor(model => model.Scores[i].Reviewer)
                    @Html.HiddenFor(model => model.Scores[i].Modifier, new { @Value = @User.Identity.Name })
                    @Html.HiddenFor(model => model.Scores[i].OderSerial)
                   
                        <p>@Model.Scores[i].ReviewName (@Model.Scores[i].Reviewer)：</p>
                        @Html.TextAreaFor(model => model.Scores[i].Comment, new { @class = "form-control", @Row = 6, @readonly = "readonly" })
                   
                </div>
            }
        </div>
       
</div>

UniPsg.Web.UI.PAS/Views/Performance/Print1.cshtml
@{
    ViewBag.Title = "Print1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Print1</h2>

UniPsg.Web.UI.PAS/Views/Performance/View1.cshtml
@{
    ViewBag.Title = "View1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View1</h2>